Add seedData functionality
AY2324S2-CS2103T-T13-4/tp pull request #40
Opened 2024-03-07 09:39 UTC by kokerinks

Closes #9

2024-03-11 05:49 UTC, billyhoce requested changes
Implementation looks good! But test cases might not be as complete, after fixing that, it should be all good!

2024-03-11 05:49 UTC, billyhoce commented on src/main/java/seedu/address/logic/commands/SeedDataCommand.java
> +        for (Person person : sampleData) {
Very good logic here that accounts for all cases (none, one, all persons already added)

2024-03-11 05:49 UTC, billyhoce commented on src/test/java/seedu/address/logic/commands/SeedDataCommandTest.java
> +        assertCommandSuccess(new SeedDataCommand(), model, SeedDataCommand.MESSAGE_SUCCESS, expectedModel);
Not very sure if this works the way I think it does, but doesn't this test case always pass as `expectedModel` and `model` is always referring to the same `Model` instance? Would it be more correct if you instanciate `expectedModel` to be a new Model containing a new `AddressBook` with the seed persons manually added into it?

2024-03-11 05:49 UTC, billyhoce commented on src/test/java/seedu/address/logic/commands/SeedDataCommandTest.java
> +        assertCommandSuccess(new SeedDataCommand(), model, SeedDataCommand.MESSAGE_SUCCESS, expectedModel);
See above comment

2024-03-11 05:49 UTC, billyhoce commented on src/test/java/seedu/address/logic/commands/SeedDataCommandTest.java
> +        assertCommandSuccess(new SeedDataCommand(), model, SeedDataCommand.MESSAGE_FAILURE, expectedModel);
See above comment

2024-03-14 16:09 UTC, billyhoce commented
Also, you might want to consider using `main/java/seedu.address/model/util/SampleDataUtil`

2024-03-15 08:57 UTC, billyhoce approved these changes

2024-03-15 09:41 UTC, kinjalagarwal1810 commented
Looks good!

2024-03-17 07:22 UTC, merged