Branch v1.2
AY2324S2-CS2103T-T13-4/tp pull request #42
Opened 2024-03-11 10:26 UTC by kinjalagarwal1810

Implemented AddPointsCommand and all the related classes & test classes for v1.2
close #1

2024-03-14 19:34 UTC, kokerinks requested changes
LGTM aside from the one comment, make sure to check codecov for un-tested lines too after the checkstyle errors are resolved

2024-03-14 19:34 UTC, kokerinks commented on src/main/java/seedu/address/logic/parser/AddPointsCommandParser.java
> +        }
I think the `ParseException` thrown by `parseName` and `parsePoints` don't have to be caught by try-catches(?)

I was referring to the scripts from e.g. `AddCommandParser.java` and this was how they handled getting values from `argMultimap`:

```
public AddCommand parse(String args) throws ParseException {
        ArgumentMultimap argMultimap =
                ArgumentTokenizer.tokenize(args, PREFIX_NAME, PREFIX_PHONE, PREFIX_EMAIL, PREFIX_ADDRESS, PREFIX_TAG);

        if (!arePrefixesPresent(argMultimap, PREFIX_NAME, PREFIX_ADDRESS, PREFIX_PHONE, PREFIX_EMAIL)
                || !argMultimap.getPreamble().isEmpty()) {
            throw new ParseException(String.format(MESSAGE_INVALID_COMMAND_FORMAT, AddCommand.MESSAGE_USAGE));
        }

        argMultimap.verifyNoDuplicatePrefixesFor(PREFIX_NAME, PREFIX_PHONE, PREFIX_EMAIL, PREFIX_ADDRESS);
        Name name = ParserUtil.parseName(argMultimap.getValue(PREFIX_NAME).get());
        Phone phone = ParserUtil.parsePhone(argMultimap.getValue(PREFIX_PHONE).get());
        Email email = ParserUtil.parseEmail(argMultimap.getValue(PREFIX_EMAIL).get());
        Address address = ParserUtil.parseAddress(argMultimap.getValue(PREFIX_ADDRESS).get());
        Set<Tag> tagList = ParserUtil.parseTags(argMultimap.getAllValues(PREFIX_TAG));

        Person person = new Person(name, phone, email, address, tagList);

        return new AddCommand(person);
    }
```

2024-03-17 06:10 UTC, billyhoce reviewed
Overall well written code and comprehensive test cases! Other than the few things mentioned, LGTM!

2024-03-17 07:23 UTC, kinjalagarwal1810 commented on src/main/java/seedu/address/logic/commands/AddPointsCommand.java
> +                .findFirst();
Yup okay makes sense!

2024-03-17 09:01 UTC, kokerinks approved these changes

2024-03-17 09:02 UTC, merged